### ISSUE TITLE
Hexagon

### ISSUE THREAD

**Issue by aliostad** [DanskeBank/MobilePay-CodeTest#2]
Hi,

I am sorry for the off-topic question but I am reaching out to find developer(s) who made the [Hexagon](https://playhexagon.com/) game. 

I saw the game in BuildStuff and I really like it and would like to use it in a talk as well as demonstration of Machine Learning and **require permission** for it. I will always use the name Danske Bank as the main author and copyright owner. 

Would be grateful if you can help me.

Thanks
Ali

**Comment by Ninfendo** [comment]
Here is the Hexagon mastermind:
https://www.linkedin.com/in/vidasvasiliauskas

**Comment by aliostad** [comment]
Thanks a lot!
